const fs = require('node:fs');
// Usage from repository root: node scripts/extract-norms.cjs path/to/TRHK-2026.html
const h = fs.readFileSync(process.argv[2],'utf8');
const clean = s => s.replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/\s+/g,' ').trim();
const all = [...h.matchAll(/<table\b[\s\S]*?<\/table>/g)].map(m => [...m[0].matchAll(/<tr\b[\s\S]*?<\/tr>/g)].map(r => [...r[0].matchAll(/<t[dh]\b[^>]*>([\s\S]*?)<\/t[dh]>/g)].map(c=>clean(c[1]))));
const tables = all.filter(t=>t[0].length===13).map(t=>t.slice(2).map(r=>[r[0]==='–'?0:Number(r[0].replace(/[^0-9]/g,'')),...r.slice(1).map(s=>Number(s.replace('%','').replace(',','.')))]));
if(tables.length!==4 || tables.some(t=>t.some(r=>r.length!==13 || r.some(n=>!Number.isFinite(n))))) throw Error('Invalid source tables');
const data={year:2026,source:'https://wetten.overheid.nl/BWBR0032503/2026-01-01#Bijlage1',retrieved:'2026-09-12',rateUpperBounds:[1.5,2,2.5,3,3.5,4,4.5,5,5.5,6,6.5],tables};
fs.writeFileSync('mortgage-norms.js','/* Official TRHK 2026, Annex 1, tables 1–4. Generated by scripts/extract-norms.cjs. */\n(function(root){const data='+JSON.stringify(data)+';if(typeof module!=="undefined"&&module.exports)module.exports=data;else root.MortgageNorms=data;})(globalThis);\n');
console.log(tables.map(t=>({rows:t.length,first:t[1][0],last:t.at(-1)[0]})));
